# IE406 Machine Learning 
## Lab Assignment 6: Principal Component Analysis

---

### Devdeep Shetrajiwala : 202001150

### Divya Patel : 202001420


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler 
import seaborn as sns
import cv2
import h5py
from sklearn.datasets import fetch_openml
import warnings
warnings.filterwarnings("ignore")

## Question 1

Given the following data use Principal Component Analysis to reduce the feature
dimension from 3 to 1 also show eigen values. (Do manual calculation)

In [5]:
# defining required array
X = np.array([[8,14,3],[13,9,6],[4,3,15],[7,2,1],[19,8,4],[5,18,11]])

# standard scaler to make mean 0 and variance 1
sc = StandardScaler()
X_std = sc.fit_transform(X)

# performing PCA
pca = PCA(n_components =1)
principalComponent = pca.fit_transform(X_std)
pComponents = pd.DataFrame(data = principalComponent , columns = ['principal component 1'])

# printing the variance ratio of each component 
print("Variance ratio: ", pca.explained_variance_ratio_)

print ("\n\nThe first principal component is: ")
print(pComponents)

print ("\n\nThe eigenvalues after the dimension reduction by PCA of the given data are :")
print(pca.components_)

Variance ratio:  [0.49991964]


The first principal component is: 
   principal component 1
0              -0.204236
1              -0.586974
2               1.740811
3              -0.710952
4              -1.708027
5               1.469378


The eigenvalues after the dimension reduction by PCA of the given data are :
[[-0.69401025  0.16586365  0.70059904]]


In [6]:
def computePCA(X):
  scaler = StandardScaler()
  X_scaled = scaler.fit_transform(X)
  means = np.mean(X_scaled, axis = 0)
  covariance_matrix=(X_scaled-means).T.dot((X_scaled-means))/(X_scaled.shape[0]-1)
  print(covariance_matrix)
  eigen_vals,eigen_vectors=np.linalg.eig(covariance_matrix)
  return [eigen_vals, eigen_vectors, X_scaled]
eig_vals, eig_vectors, X_scaled = computePCA(X)

[[ 1.2        -0.04772727 -0.58277152]
 [-0.04772727  1.2         0.09470037]
 [-0.58277152  0.09470037  1.2       ]]


In [7]:
print(f'\nEigen Values = {eig_vals}')
print(eig_vectors[: , 0])
final_feature=(X_scaled).dot(eig_vectors[: , 0])
print(final_feature)


Eigen Values = [1.79971072 0.61531314 1.18497614]
[-0.69401025  0.16586365  0.70059904]
[-0.20423593 -0.58697404  1.74081123 -0.71095189 -1.70802694  1.46937756]


In [8]:
#MANUAL CALCULATION
from numpy import mean
from numpy import cov
from numpy import array
from numpy.linalg import eig

# calculating the mean of each column
Mean = mean(X.T, axis=1)

# determining center columns by subtracting column means
X_STD = X - Mean

# calculating covariance matrix of centered matrix
Va = cov(X_STD.T)

# eigendecomposition of covariance matrix
values, vectors = eig(Va)
print("Eigen Vectors :\n",vectors,'\n')
print("Eigen Values :\n",values,'\n')

# projectnig the data
Prj = vectors.T.dot(X_STD.T)
print(Prj.T)

Eigen Vectors :
 [[ 0.65370829  0.70071725 -0.28576354]
 [-0.04563208 -0.34043372 -0.93916058]
 [ 0.75536957 -0.62697704  0.19056916]] 

Eigen Values :
 [15.41684401 46.07005232 37.44643701] 

[[-3.86945988 -0.33754247 -5.01353842]
 [ 1.89335068  2.98728129 -1.17484576]
 [ 3.08209469 -6.91936503  8.74711203]
 [-5.48632232  4.30089903  6.16101375]
 [ 4.35049337  8.78597262 -2.33140475]
 [ 0.02984346 -8.81724545 -6.38833684]]


## Question 2

A classic application of PCA is to project the 3-D point cloud onto a plane that could still retain the information or essence of the point distribution. Given a 3-D point cloud, estimate an optimal plane, onto which if the 3D data points when projected would still retain the essential information. We provide you with 5 different point clouds P_1.txt to P_5.txt containing the 3D coordinates of points in space. Perform PCA on these point clouds to obtain their projection on a 2D plane and visualize the results using python libraries (like matplotlib).